### ISSUE TITLE
compiler warnings

### ISSUE THREAD

**Issue by dodol** [bgrimstad/multivariate-splines#3]
when compiled with -Wall -Wextra -pedantic:
lots of warning of type  "comparison between signed and unsigned integer expressions [-Wsign-compare]" 
due to variable Basis1D::degree being declared as int. I guess that degree cannot be less than 0, and therefore can be declared as unsigned int. 
Same thing goes for num_knots in Basis1D::knotSequenceFree and elsewhere.

In BSpline::computeControlPoints the line bspline.cpp:378, i.e. 
bool successfulSolve = (s.solve(Ad,Bx,Cx) && s.solve(Ad,By,Cy)); 
triggers warning: unused variable ‘successfulSolve’ [-Wunused-variable]
Since the variable is used in assert fun below, one could write 
assert(s.solve(Ad,Bx,Cx) && s.solve(Ad,By,Cy));
and many more similar warnings dealing with [-Wsign-compare] and [-Wunused-variable].

**Comment by bgrimstad** [comment]
This issue has been addressed in the development branch.
